### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by gayathchandula** [vighnesh-21/Drunkenness-Face-Detection-Using-Graph-Neural-Network#1]
Can I get the notebook file for model training

**Comment by vighnesh-21** [comment]
> Can I get the notebook file for model training

This is a product based project , which is still under development. We will open source the data and the code post final development of our product.

**Comment by gayathchandula** [comment]
Is there any possibility to get the dataset then? Because i'm doing
academic project and its hard to find a drunk dataset
